---
  - name: install common packages
    action: apt name=$item update-cache=yes state=installed
    with_items:
      - zsh
      - vim
      - git
      - tmux
  - name: ntp is installed
    apt: name=ntp state=installed
    tags: ntp

  - name: ntp is configured
    template: src=ntp.conf.j2 dest=/etc/ntp.conf
    notify:
      - restart ntpd
    tags: ntp

  - name: ntpd is running and enabled
    service: name=ntp state=running enabled=yes
    tags: ntp

  - name: Determining username
    action: shell whoami
    register: whoami
    sudo: False
  - name: Changing the default shell to zsh
    action: user shell=/bin/zsh user=$item
    with_items:
      - root
      - ${whoami.stdout}