---
  - name: ensure postgresql repository setup key
    tags: postgresql
    action: apt_key url=https://www.postgresql.org/media/keys/ACCC4CF8.asc state=present

  - name: ensure postgresql repository
    tags: postgresql
    action: apt_repository repo="deb http://apt.postgresql.org/pub/repos/apt/ precise-pgdg main"

  - name: Install PostgreSQL
    tags: postgresql
    action: apt name=$item update-cache=yes state=installed
    with_items:
     - postgresql-9.3
     - postgresql-contrib-9.3
     - postgresql-server-dev-9.3
     - postgresql-client-9.3
     - postgresql-9.3-pgpool2

  - name: Install psycopg2 (needed for Ansible)
    tags: postgresql
    apt: pkg=python-psycopg2 update-cache=yes state=latest
